### ISSUE TITLE
Use mas for Mac App Store automation

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mac-dev-playbook#11]
See: https://github.com/argon/mas

This would be nice to get even the Mac App Store stuff automated. Or maybe just a second playbook that you can run once authenticated, something like that.

**Comment by geerlingguy** [comment]
See: https://github.com/TravisCarden/dotfiles/blob/master/playbooks/tasks/mac-app-store.yml

Idempotent example:

```yaml
- name: Install Mac App Store apps.
  shell: mas list | grep {{ item }} || mas install {{ item }}
  with_items:
    - 407963104 # Pixelmator
    - ...
  register: result
  changed_when: result.stdout.find('Installed') != -1
```

**Comment by fubarhouse** [comment]
+1.

**Comment by fubarhouse** [comment]
Here's a small variation, which improves readability.
Tested and verified, so I'm not sure what's holding this one back.

vars/main.yml
````
#
# Mac Apple Store
#
# Apps to install from the app store.
# Array of App ID's will only validate.
#

mac_store_apps:
  - name: blackmagic-disk-speed-test
    id: 425264550
````

main.yml
````
    - include: tasks/mac-apple-store.yml
      when: '"mas" in homebrew_installed_packages'
````

tasks/mac-apple-store.yml
````
- name: Mac Apple Store | Install apps.
  shell: mas list | grep "{{ item.id }}" || mas install "{{ item.id }}"
  with_items: "{{ mac_store_apps }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1
````

This modification changes the structure of the array of processed items, to show the name as well as the mac id. The name was simply pulled from the URL, however I plan on making it better for my playbook - but the name isn't actually used by Ansible but it serves as a valuable non-comment entry to authors to identify what's what.

**Comment by geerlingguy** [comment]
@fubarhouse - Thanks for your work on this—one of the last components would be to document how to get `mas` initialized, or if it can be done automatically during the playbook run, maybe using an Ansible `prompt` to get the `mas` username/password...

I wouldn't want the playbook to hang the first time it's run because `mas` was just installed and isn't able to actually connect to the App store.

**Comment by fubarhouse** [comment]
### Revision 2

Changes as requested, see full list of changes from the master below.

Let me know if you're happy and I can create a PR.

#### Observations

- MAS will request a username/password using the Apple store on OSX (not command-line) when you're requesting a download but not logged in.

#### vars/main.yml

````
install_mas_products: yes
````

````
#
# Mac Apple Store
#
# Apps to install from the app store.
# Array of App ID's will only validate.
#

mac_store_apps:
  - name: BlackMagic Disk Speed test
    id: 425264550
  - name: Microsoft OneDrive
    id: 823766827
````

#### main.yml
````
  vars_prompt:
  - name: app_store_email
    prompt: Mac Apple Store ID:
    private: no
  - name: app_store_password
    prompt: Mac Apple Store Password:
    private: yes
````

````
    - include: tasks/mac-apple-store.yml
      when: install_mas_products
````

#### tasks/mac-apple-store.yml

````
---
- name: Mac Apple Store | Ensure MAS is installed
  homebrew:
    name: mas
    state: present

- name: Mac Apple Store | Signing out
  shell: "mas signout"
  register: mac_account
  when: app_store_email is defined and app_store_password is defined

- name: Mac Apple Store | Signing in.
  shell: "mas signin \"{{ app_store_email }}\" \"{{ app_store_password }}\""
  register: result
  when: app_store_email is defined and app_store_password is defined and mac_account is defined

- name: Mac Apple Store | Install apps.
  shell: mas list | grep "{{ item.id }}" || mas install "{{ item.id }}"
  with_items: "{{ mac_store_apps }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1

- name: Mac Apple Store | Upgrade apps.
  shell: mas list | grep "{{ item.id }}" || mas upgrade "{{ item.id }}"
  with_items: "{{ mac_store_apps }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1

````
