### ISSUE TITLE
Dock control tasks skipped if dockutil not installed or not in PATH

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mac-dev-playbook#112]
I have the default playbook set up with the following in my `config.yml`:

```yaml
configure_dock: true
dockitems_remove:
  - Launchpad
  - Maps
  - FaceTime
  - Contacts
  - Reminders
  - TV
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages
  - 'App Store'
dockitems_persist: []
```

When I run the playbook I see:

```
TASK [Ensure unwanted dock items removed.] *******************************************************
skipping: [127.0.0.1]

TASK [find if dock item exists] ******************************************************************
ok: [127.0.0.1]

TASK [Ensure unwanted dock items removed.] *******************************************************
skipping: [127.0.0.1]

TASK [find if dock item exists] ******************************************************************
ok: [127.0.0.1]
... (repeats)
```

It looks like `dockutil` is not installed:

```
jgeerling@Jeffs-MacBook-Air mac-dev-playbook % dockutil --find TV                       
zsh: command not found: dockutil
```

And because of the `failed_when` override in those tasks, they don't fail if `dockutil` is not present.

So I need to make sure if `configure_dock: true` is set, then `dockutil` is installed. I should maybe create a separate role for the Dock stuff...
