### ISSUE TITLE
mas tasks are skipped if you only supply 'mas_installed_app_ids'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mac-dev-playbook#113]
In my case, I like to be able to easily dump/translate `mas list` into my `config.yml`, so I get something like:

```yaml
mas_installed_app_ids:
  - 424389933   # Final Cut Pro             (10.5.2)
  - 405537804   # Sound Studio              (4.9.6)
```

But when I run the playbook with that setting, I end up with:

```
TASK [geerlingguy.mas : Get MAS account status] ***********
skipping: [127.0.0.1]
```

Because the current check for including the role is:

```yaml
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
```

A workaround is to set `mas_installed_apps: true`, but that could have other weird unintended consequences...
