### ISSUE TITLE
PATH issues when running against macOS 11.4 (Big Sur)

### ISSUE THREAD

**Issue by natelandau** [geerlingguy/mac-dev-playbook#132]
On Big Sur the `Dock` and `Mas` plugins do not work due to PATH issues.  The commands in the playbooks assume the `/usr/local/bin` is in the PATH, but it is not.  I have not tested this playbook on another version of macOS, so I'm not sure if this issue exists outside of Big Sur.

For example, this command in the geerlingguy.mac.dock role calls `dockutil` (confirmed to be installed in `/usr/local/bin`)
```yaml
- name: "See if {{ item }} is in the Dock."
  ansible.builtin.command:
    cmd: dockutil --find '{{ item }}'
  register: dockitem_exists
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  tags: ['dock']
```

results in:

```yaml
ok: [NEW_MAC] => changed=false 
  cmd: dockutil --find 'App Store'
  failed_when_result: false
  invocation:
    module_args:
      _raw_params: dockutil --find 'App Store'
      _uses_shell: false
      argv: null
      chdir: null
      creates: null
      executable: null
      removes: null
      stdin: null
      stdin_add_newline: true
      strip_empty_ends: true
      warn: false
  msg: '[Errno 2] No such file or directory'
  rc: 2
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
To confirm it is a PATH issue, I created a test task to print the available PATH

```yaml
- name: test path
  ansible.builtin.command:
    cmd: "echo $PATH"
  register: test_PATH

- debug:
    msg: "{{ test_PATH.stdout }}"
```
which results in 
```yaml
ok: [NEW_MAC] => 
  msg: /usr/bin:/bin:/usr/sbin:/sbin
```

Fixing these roles, would be relatively easy by simply adding the PATH before each command. However, I don't like the idea of forking my code and diverging from the galaxy versions.  Is there a way to fix this issue without needing to customize the collections/roles themselves?

**Comment by natelandau** [comment]
A bit more digging on why the homebrew tasks works shows that these lines in `geerlingguy.mac.homebrew > defaults > main/yml` set the appropriate PATH as an available variable.  Perhaps this functionality needs to be extended to the `Mas` and `Dock` roles.

```yaml
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
```
