### ISSUE TITLE
Add ability to control dock items

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/mac-dev-playbook#19]
The following blog entry shows how we can control dock items and position with your existing homebrew role.

`https://blog.vandenbrand.org/2016/01/04/how-to-automate-your-mac-os-x-setup-with-ansible/`

It would be freaking awesome to control this through your role too! I'll be using it in my forks regardless, but this is a legitimate improvement which adds to the value and purpose of this role.

vars/main.yml additions

```
dockitems_disabled:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Terminal

dockitems_enabled:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Tower
    path: "/Applications/Tower.app"
    pos: 2
  - name: FirefoxDeveloperEdition
    path: "/Applications/FirefoxDeveloperEdition.app"
    pos: 3
  - name: Sublime Text
    path: "/Applications/Sublime Text.app"
    pos: 4
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 5
  - name: JetBrains Toolbox
    path: "/Applications/JetBrains Toolbox.app"
    pos: 6
  - name: TeavViewer
    path: "/Applications/TeamViewer.app"
    pos: 7
```

tasks/dockutil.yml:

```
- name: Dockutil | Remove all unwanted dock items
  shell: dockutil --remove "{{ item }}"
  ignore_errors: true
  with_items: "{{ dockitems_disabled }}"
  when: "{{ dockitems_disabled | length > 0 }}"

- name: Dockutil | Adding items
  shell: dockutil --find "{{ item.name }}" || dockutil --add "{{ item.path }}"
  with_items: "{{ dockitems_enabled }}"
  when: "{{ dockitems_enabled | length > 0 }}"

- name: Dockutil | Moving items
  shell: dockutil --move "{{ item.name }}" --position "{{ item.pos }}"
  with_items: "{{ dockitems_enabled }}"
  when: "{{ dockitems_enabled | length > 0 }}"
```

**Comment by oxyc** [comment]
Posting for others who happen to find this feature interesting. @fubarhouse has a role that manages the dock https://github.com/fubarhouse/ansible-role-macdock. Works great with `persistent-apps` dock items but doesn't support `persistent-others`. Should be enough for most though.

**Comment by fubarhouse** [comment]
Yep, it was something needed for work so I took it on properly.

Interesting about `persistent-others`, I hadn't actually heard of that before now.

Still a worthwhile feature for mac-dev-playbook - in my personal opinion.

**Comment by geerlingguy** [comment]
Yeah, I'm planning on adding support when I get the time; thanks for contributing that role!

**Comment by geerlingguy** [comment]
Ooh, @oxyc also pointed me to https://github.com/kinglouie/ansible-role-macos

See the example configuration here: https://github.com/kinglouie/ansible-role-macos/blob/master/defaults/main.yml#L227-L259

For something like controlling apps in the dock, it looks as simple as:

```yaml
dock:
  apps:
    - name: Safari
      path: /Applications/Safari.app
  spacers:
    - after: Safari
```
