### ISSUE TITLE
Add Sublime configuration and package manager setup

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/mac-dev-playbook#20]
In  the README and playbook you've stated you wanted sublime to be configured.

Purely for your information, here's how I've done it - but I based mine off Drupal.org's recommended sublime configuration. (`https://www.drupal.org/docs/develop/development-tools/configuring-sublime-text`)

The recommended script is here: `https://github.com/enzolutions/sublime-drupal` or more directly `https://raw.githubusercontent.com/enzolutions/sublime-drupal/master/SublimeDrupal.sh`.

I haven't covered all of the scripts functionality, but I've covered a lot of it.

tasks/sublime.yml

```
- name: Sublime | Copying configuration
  copy:
    src: "./files/sublime/Library/Packages/User/Preferences.sublime-settings"
    dest: "{{ sublime_dir }}/{{ sublime_packages_dir }}/User/Preferences.sublime-settings"

- name: Sublime | Install Package Manager
  get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_dir }}/{{ sublime_packageman_dir }}/Package Control.sublime-package"

- name: Sublime | Install Packages
  git:
    repo: "{{ item.repo }}"
    dest: "{{ sublime_dir }}/{{ sublime_packages_dir }}/{{ item.name }}"
    clone: yes
    update: yes
    force: yes
    accept_hostkey: yes
  become: no
  with_items: "{{ sublime_packages }}"
```

vars/main.yml

```
sublime_dir: ~/Library/Application Support/Sublime Text 3
sublime_packages_dir: "Packages"
sublime_packageman_dir: "Installed Packages"
sublime_packageman_file: https://packagecontrol.io/Package%20Control.sublime-package
sublime_packages:
- name: Colorsublime
  repo: https://github.com/Colorsublime/Colorsublime-Plugin.git
- name: DrupalSublimeConfig
  repo: https://github.com/enzolutions/drupal-sublime-config.git
- name: BracketHighlighter
  repo: https://github.com/facelessuser/BracketHighlighter.git
- name: Highlighter
  repo: https://github.com/bluegray/Highlighter.git
- name: ApplySyntax
  repo: https://github.com/facelessuser/ApplySyntax.git
- name: PrettyYAML
  repo: https://github.com/aukaost/SublimePrettyYAML.git
- name: Dracula Color Scheme
  repo: https://github.com/dracula/textmate.git
- name: Darkula
  repo: https://github.com/mattchanner/darkula.git
- name: DocBlockr
  repo: https://github.com/spadgos/sublime-jsdocs.git
- name: Sublime-Text-2-Goto-Drupal-API
  repo: https://github.com/BrianGilbert/Sublime-Text-2-Goto-Drupal-API.git
- name: DrupalSublimeSnippets
  repo: https://github.com/juhasz/drupal_sublime-snippets.git
- name: DrupalCodingStandard
  repo: https://github.com/rypit/DrupalCodingStandard.git
- name: sublime-text-2-goto-documentation
  repo: https://github.com/kemayo/sublime-text-2-goto-documentation.git
- name: SyncedSideBar
  repo: https://github.com/sobstel/SyncedSideBar.git
- name: TrailingSpaces
  repo: https://github.com/SublimeText/TrailingSpaces.git
- name: st2-drupal-autocomplete
  repo: https://github.com/tanc/st2-drupal-autocomplete.git
- name: sublime-find-function-definition
  repo: https://github.com/timdouglas/sublime-find-function-definition.git
- name: sublime-text-2-git
  repo: https://github.com/kemayo/sublime-text-2-git.git
- name: GitGutter
  repo: https://github.com/jisaacks/GitGutter.git
- name: SideBarGit
  repo: https://github.com/SublimeText/SideBarGit.git
- name: SublimeLinter
  repo: https://github.com/SublimeLinter/SublimeLinter.git
- name: SASS
  repo: https://github.com/nathos/sass-textmate-bundle.git
- name: SideBarEnhancements
  repo: https://github.com/titoBouzout/SideBarEnhancements.git
- name: CssSnippets
  repo: https://github.com/P233/Emmet-Css-Snippets-for-Sublime-Text-2.git
- name: JSLint
  repo: https://github.com/darrenderidder/Sublime-JSLint.git
- name: MacTerminal
  repo: https://github.com/afterdesign/MacTerminal.git
- name: Theme - Soda
  repo: https://github.com/buymeasoda/soda-theme.git
```
