### ISSUE TITLE
Do not overwrite sudoers file

### ISSUE THREAD

**Issue by mkwardakov** [geerlingguy/mac-dev-playbook#33]
Since it could have modifications already.
Better use lineinfile module.

**Comment by tomtastic** [comment]
You really really should be putting your config in /etc/sudoers.d/
There is **no need** to edit the main /etc/sudoers file.

**Comment by tomtastic** [comment]
Please put the vagrant sudoers config into `/etc/sudoers.d/vagrant` instead.
You can validate in the same way with `visudo -cf /etc/sudoers.d/vagrant`

**Comment by geerlingguy** [comment]
It seems like at least in Catalina it's in `/private/etc/sudoers.d` (or is `/etc/sudoers.d` an alias to that path?).

I agree, it would be better to add custom config in there instead of modifying the main `sudoers` file...

Note that if you have `configure_sudoers: false` then no modifications are made (to @mkwardakov 's original issue). Also, I like using a template instead of `lineinfile` for any arbitrarily-configurable options.

**Comment by geerlingguy** [comment]
See above commit; now you can add a custom config like:

```yaml
configure_sudoers: yes
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL
```

And it will dump the string in the config var into a file in `/etc/sudoers.d/custom`.
