### ISSUE TITLE
Ways to install non-brew packages.

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/mac-dev-playbook#35]
I personally have a few projects I want to install that aren't available as brew formulas.

Some examples:
- https://github.com/chriskempson/base16-shell
  This is a library I source from my dot files. The installation would basically require to checkout the repo into a specified folder.
- https://github.com/oxyc/vimrc
  This is my personal vimrc configurations. The installation requires git checkout and `make install`.
- https://github.com/kovidgoyal/kitty
   Just found this one and going to try it out. It doesn't have a brew formula but does have a dmg that you can download.

Not sure how to automate the installation of `dmg` packages in a proper way, but I'll look into it. One idea that would make the playbook flexible enough to install my first two requirements is:

```
extra_git_installs:
  - repo: https://github.com/chriskempson/base16-shell
    destination: ~/.local/lib/base16-shell
  - repo: git@github.com:oxyc/vimrc.git
    destination: ~/Projects/Personal/vimrc
    accept_hostkey: yes
    install_command: "make install"
```

Thoughts? Should I just keep this in my fork or might something like this be useful for you or others?

**Comment by oxyc** [comment]
Regarding the dmg installation, I just added my own tap and install it with brew. Easy enough and more inline with macOS installations. https://github.com/oxyc/homebrew-custom/blob/master/Casks/kitty.rb

https://github.com/oxyc/mac-dev-playbook/commit/d2d84899a80390052a4c7bab2da02c73a3d33d94

**Comment by oxyc** [comment]
Another solution would be something like:

```yaml
extra_shell_commands:
  - "brew services start khd"
  - "vagrant plugin install vagrant-hostsupdater"
  - "vagrant plugin install vagrant-vbguest"

post_provision_scripts:
  - scripts/bash4.sh
  - scripts/vimrc.sh
```
