### ISSUE TITLE
Post provision script

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/mac-dev-playbook#37]
Part of my bootstrap is switching to bash4 but this requires a manual command to add it to change the login shell.

```bash
if ! grep -Fxq "/usr/local/bin/bash" /etc/shells; then
  echo /usr/local/bin/bash >> /etc/shells
  sudo -u oxy 'chsh -s /usr/local/bin/bash'
fi
```

Interested in adding `post_provision_scripts`? Feel free to simply close any of these suggestions–I'll use a fork either way but posting in case you're interested.

**Comment by oxyc** [comment]
Closing as duplicate of #35.

**Comment by oxyc** [comment]
For reference, to switch the default shell for the user I now rely on #43 together with this variable:

```yaml
local_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
```

And these tasks

```yaml
---
- name: Ensure brew installed Bash is listed as an acceptable shell.
  lineinfile:
    path: /etc/shells
    line: "/usr/local/bin/bash"
  become: yes
  when: "'bash' in homebrew_installed_packages"

- name: Change user shell to brew installed Bash.
  command: "chsh -s /usr/local/bin/bash {{ local_user }}"
  register: chsh_result
  changed_when: chsh_result.rc != 0
  become: yes
  when: "'bash' in homebrew_installed_packages"
```
