### ISSUE TITLE
pip packages not installed with flag: --tags "extra-packages"

### ISSUE THREAD

**Issue by madismaks** [geerlingguy/mac-dev-playbook#97]
Not sure if I'm missing something, but when running:

`ansible-playbook main.yml -i inventory --tags "extra-packages"`

pip packages listed in `config.yml` are not installed. Ansible tells that the the file containing relevant task is included:

`included: /Users/test/git/mac-dev-playbook/tasks/extra-packages.yml for 127.0.0.1`

but nothing gets installed. The same Ansible command above works when I'm adding  `tags: ['extra-packages']` to the task in `extra-packages.yml` explicitly, e.g. like this:

```
- name: Install global Pip packages.
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ pip_packages }}"
  tags: ['extra-packages']
```

If I run:

`ansible-playbook main.yml -i inventory -K`

it installs the pip packages as expected, but since there's this sentence in README:

> The tags available are dotfiles, homebrew, mas, extra-packages and osx.

I would have assumed the `--tags "extra-packages"` works as well.

Steps for reproducing:

`git clone https://github.com/geerlingguy/mac-dev-playbook.git`
`cd mac-dev-playbook && ansible-galaxy install -r requirements.yml`

```
cat <<'EOF' >> config.yml
---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

homebrew_uninstalled_packages:
  - pv

homebrew_installed_packages:
  - pv

homebrew_cask_appdir: /Applications

homebrew_cask_uninstalled_apps:
  - chromedriver

homebrew_cask_apps:
  - chromedriver

pip_packages:
  - mkdocs
EOF
```

`ansible-playbook main.yml -i inventory --tags "extra-packages"` - this does not install `mkdocs` pip package
`ansible-playbook main.yml -i inventory -K` - this installs `mkdocs` pip package
